version: 1.0.{build}

before_build:
  - nuget restore

build:
  verbosity: minimal

artifacts:
- path: /bin
  name: binaries

deploy:
- provider: GitHub
  auth_token:
    secure: 8Cx6MFrE/49EAos6kgdEFHkAUJOPIazE1rwmOg1A0DUZ0D8uklB/3T7ur/2sXtY+JL1SO3o3r7jQeYWRtvnZQnNM6vQHEYe7h6FEk0OfU4o=
  artifact: vv