version: 1.0.{build}
configuration: Release

environment:
  github_token_crypted: 
    secure: BI8CvihIl1X5UtJJ4aQn5yyO1v0rgga8iMqK9sZmm7s6qZQG+VNUKa5PDNhQrteN
  NUGET_TOKEN_CRYPTED:
    secure: El3Kj0SEU9/+Di2uXiCsTGlDWSjPcqXyO2drOT3XDGOp3rMdIX8zeXOBZLlOCQZw

before_build:
- cmd: nuget restore

build:
  verbosity: minimal

artifacts:
- path: src\bin\$(configuration)
  name: ProxyMySystem-v$(appveyor_build_version)

deploy:
- provider: GitHub
  release: portable-v$(appveyor_build_version)
  auth_token: $(github_token_crypted)
  artifact: ProxyMySystem-v$(appveyor_build_version).zip
