version: 1.5.{build}
configuration: Release

skip_commits:
  files:
    - '**/*.md'

install:
  - choco install gitversion.portable -pre -y

environment:
  APPVEYOR_REPO_TAG: true
  GITHUB_TOKEN_CRYPTED: 
    secure: BI8CvihIl1X5UtJJ4aQn5yyO1v0rgga8iMqK9sZmm7s6qZQG+VNUKa5PDNhQrteN
  NUGET_TOKEN_CRYPTED:
    secure: El3Kj0SEU9/+Di2uXiCsTGlDWSjPcqXyO2drOT3XDGOp3rMdIX8zeXOBZLlOCQZw

before_build:
- cmd: nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
- cmd: git log 1.1.0...HEAD --pretty=format:"- %h %s" > NOTES.md

build:
  verbosity: minimal

artifacts:
- path: src\bin\$(configuration)
  name: ProxyMySystem-v$(appveyor_build_version)

deploy:
- provider: GitHub
  auth_token:
    secure: BI8CvihIl1X5UtJJ4aQn5yyO1v0rgga8iMqK9sZmm7s6qZQG+VNUKa5PDNhQrteN
  artifact: ProxyMySystem-v$(appveyor_build_version)
  force_update: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
